title: Kuba Andrýsek
subtitle: Moje projekty
description: >- # this means to ignore newlines until "baseurl:"
  Jmenuji se Jakub Andrýsek, ale všichni mi říkají Kubo. Jsem 3D modelář a programátor v Robotárně.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "kubaandrysek-website" # the subpath of your site, e.g. /blog

urls:
    - text: O mě
      url: /about
    - text: Projekty
      url: /blog
    - text: Galerie
      url: /gallery
    - text: Kontakt
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Kuba Andrýsek
author_bio: Jmenuji se Jakub Andrýsek, ale všichni mi říkají Kubo. Jsem 3D modelář a programátor v Robotárně. #Hello, My Name is John Doe. I love to Code and Design. devlopr-jekyll is a theme built for developers.
author_email: "email@kubaandrysek.cz"
author_location: Czech republic
author_website_url: "https://kubaandrysek.cz"

author_work_experiences:
            - designation: Dvě 1. místa na robotickém dni v Praze
              company_name: červen 2019
              description: V kategoriích Toy Cleanup a Roadside Assistance
              company_logo: google.png
              company_url: http://robotickyden.cz                        
              visibility: true
            - designation: 1. místo v programátorské soutěži
              company_name: březen 2019
              description: 
              company_logo: google.png
              company_url: 
              visibility: true

author_education_details:
              - college_logo: gvid.jpg
                college_name: Gymnázium Brno, Vídeňská, příspěvková organizace
                college_url: http://www.gvid.cz
                description: Šestileté gymnázium zaměřené na informatikul
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: 
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
github_username:  JakubAndrysek
# facebook_username: johndoe
linkedin_username: jakub-andrysek
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

## Pro sprovozneni komentaru!!
#for comments using disqus
# disqus_shortname: sujay-kundu

# wakatime username (coding activity)
wakatime_username: KubaAndrysek

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: email@kubaandrysek.cz

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: XH3020M2M2 #D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: e2d65805318c9e4170af258817cdddbd #58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build